 import type { Locale } from "@manzil/shared";

const copy = {
  uz: {
    menu: {
      section: "Asosiy menyu",
      overview: "Boshqaruv paneli",
      bookings: "Bandlovlar",
      announcements: "E'lonlar",
      packages: "Xizmatlar va narxlar",
      reviews: "Sharhlar",
      analytics: "Tahlil",
      customers: "Mijozlar",
      settings: "Sozlamalar",
      plan: "Tarif",
      upgrade: "Tarifni oshirish",
      viewPublic: "Ochiq sahifani ko'rish",
      partnerPortal: "Hamkorlar portali",
      mobileMenu: "Menyu"
    },
    overview: {
      title: "Boshqaruv paneli",
      visits30: "Tashriflar (30 kun)",
      unique30: "Noyob mehmonlar",
      reviewsTotal: "Jami sharhlar",
      avgRating: "O'rtacha baho",
      vsNote: "so'nggi 30 kun",
      last7: "so'nggi 7 kunda",
      visitsChart: "Kunlik tashriflar",
      ratingDist: "Baholar taqsimoti",
      completeness: "Profil to'liqligi",
      completenessHint: "To'liq profil qidiruvda yuqoriroq ko'rinadi.",
      published: "Chop etilgan e'lonlar",
      activePackages: "Faol xizmatlar",
      pendingNote: "Biznesingiz admin tasdig'ini kutmoqda. Tasdiqdan so'ng profil ochiq sahifada ko'rinadi.",
      welcome: "Xush kelibsiz! Biznesingizning bugungi holati quyida.",
      totalBookings: "Jami bandlovlar",
      revenue: "Tushum",
      activeDiscounts: "Faol chegirmalar",
      businessHealth: "Biznes holati",
      rangeWeek: "Hafta",
      rangeMonth: "Oy",
      recentBookings: "So'nggi bandlovlar",
      viewAll: "Barchasini ko'rish",
      statusClaimed: "Tasdiqlangan",
      statusPending: "Tasdiq kutilmoqda"
    },
    bookings: {
      title: "Bandlovlar",
      subtitle: "Telefon orqali yoki kelib qabul qilingan bandlovlarni shu yerda yozib boring.",
      newTitle: "Yangi bandlov",
      customerPhone: "Mijoz telefoni",
      serviceName: "Xizmat",
      startsAt: "Boshlanish vaqti",
      endsAt: "Tugash vaqti (ixtiyoriy)",
      depositAmount: "Depozit, so'm (ixtiyoriy)",
      submit: "Bandlovni qo'shish",
      submitting: "Saqlanmoqda…",
      upcoming: "Yaqinlashayotgan",
      filterAll: "Barchasi",
      table: {
        customer: "Mijoz",
        phone: "Telefon",
        service: "Xizmat",
        when: "Vaqti",
        status: "Holat",
        actions: "Amallar"
      },
      statuses: {
        pending: "Kutilmoqda",
        confirmed: "Tasdiqlangan",
        canceled: "Bekor qilingan",
        completed: "Bajarildi",
        no_show: "Kelmadi"
      },
      confirm: "Tasdiqlash",
      confirming: "Tasdiqlanmoqda…",
      complete: "Bajarildi deb belgilash",
      completing: "Belgilanmoqda…",
      cancel: "Bekor qilish",
      canceling: "Bekor qilinmoqda…",
      noShow: "Kelmadi deb belgilash",
      noShowing: "Belgilanmoqda…",
      emptyTitle: "Hozircha bandlovlar yo'q",
      emptyBody:
        "Mijoz telefon qilib yoki do'konga kelib navbat olganda, shu yerga yozib qo'ying. Bandlov \"Bajarildi\" deb belgilanganda mijoz avtomatik ravishda Mijozlar ro'yxatiga qo'shiladi va keyin sharh qoldirsa \"tasdiqlangan tashrif\" belgisini oladi.",
      noEndsAt: "—"
    },
    announcements: {
      title: "E'lonlar",
      subtitle: "Yangiliklar, chegirmalar va xabarlarni chop eting.",
      newTitle: "Yangi e'lon",
      kind: "Turi",
      kinds: { news: "Yangilik", discount: "Chegirma", broadcast: "Xabar" },
      formTitle: "Sarlavha",
      formBody: "Matn",
      discountPercent: "Chegirma (%)",
      startsAt: "Boshlanish sanasi",
      endsAt: "Tugash sanasi",
      submit: "Chop etish",
      saveDraft: "Qoralama sifatida saqlash",
      statuses: { draft: "Qoralama", published: "Chop etilgan", archived: "Arxiv" },
      publish: "Chop etish",
      archive: "Arxivlash",
      remove: "O'chirish",
      empty: "Hozircha e'lonlar yo'q.",
      table: { title: "Sarlavha", kind: "Turi", status: "Holat", date: "Sana", actions: "Amallar" }
    },
    packages: {
      title: "Xizmatlar va narxlar",
      subtitle: "Xizmatlar ro'yxati mijozlarga ochiq sahifada ko'rinadi.",
      newTitle: "Yangi xizmat",
      name: "Nomi",
      description: "Tavsif",
      price: "Narx (so'm)",
      submit: "Qo'shish",
      activate: "Faollashtirish",
      deactivate: "To'xtatish",
      remove: "O'chirish",
      empty: "Hozircha xizmatlar yo'q.",
      table: { name: "Xizmat", price: "Narx", status: "Holat", actions: "Amallar" },
      active: "Faol",
      inactive: "Faol emas"
    },
    reviews: {
      title: "Sharhlar",
      subtitle: "Mijozlar sharhlariga rasmiy javob bering.",
      empty: "Hozircha sharhlar yo'q.",
      reply: "Javob yozish",
      replyPlaceholder: "Rasmiy javob matni",
      send: "Yuborish",
      replied: "Javob berilgan",
      exportCsv: "CSV yuklab olish"
    },
    settings: {
      title: "Sozlamalar",
      subtitle: "Biznes ma'lumotlari ochiq sahifada ko'rinadi.",
      profile: "Biznes ma'lumotlari",
      name: "Nomi",
      legalName: "Yuridik nomi",
      taxId: "STIR (9 raqam)",
      address: "Manzil",
      district: "Tuman",
      phone: "Telefon",
      email: "Email",
      website: "Veb-sayt",
      instagram: "Instagram",
      telegram: "Telegram",
      hours: "Ish vaqti",
      description: "Tavsif",
      save: "Saqlash",
      subscription: "Obuna",
      plan: "Tarif",
      status: "Holat",
      renews: "Keyingi to'lov",
      subStatuses: {
        active: "Faol",
        trial: "Sinov",
        invoice_pending: "To'lov kutilmoqda",
        canceled: "Bekor qilingan"
      }
    },
    register: {
      title: "Biznesni ro'yxatdan o'tkazish",
      subtitle:
        "Ma'lumotlarni to'ldiring. Ariza admin tomonidan ko'rib chiqiladi va tasdiqlangach kabinet to'liq ochiladi.",
      basics: "Asosiy ma'lumotlar",
      category: "Kategoriya",
      contactSection: "Aloqa",
      legalSection: "Yuridik ma'lumotlar (O'zbekiston)",
      legalHint: "STIR ixtiyoriy, lekin tasdiqlashni tezlashtiradi.",
      submit: "Ro'yxatdan o'tkazish",
      submitting: "Yuborilmoqda…",
      failedTitle: "Ro'yxatdan o'tkazib bo'lmadi",
      failedBody: "Ma'lumotlar saqlanmadi. Qaytadan urinib ko'ring — takroriy biznes yaratilmaydi.",
      retry: "Qaytadan urinish",
      signInFirst: "Avval tizimga kiring",
      signInText: "Biznesni ro'yxatdan o'tkazish uchun hisob talab qilinadi.",
      signIn: "Kirish",
      brandWordmark: "Manzil — biznes uchun",
      brandTagline: "Mahalliy biznesingizni rivojlantiring.",
      brandSubline:
        "Manzil'da profil oching — mijozlar sizni topadi, sharh qoldiradi va siz bilan bog'lanadi.",
      mobileKicker: "Hamkorlar portalida ro'yxatdan o'tish",
      namePlaceholder: "Masalan: Chinor Kafe",
      categoryPlaceholder: "Kategoriyani tanlang",
      signUpPrompt: "Hisobingiz yo'qmi?",
      signUpCta: "Ro'yxatdan o'tish"
    },
    plans: {
      title: "Tarifni tanlang",
      subtitle: "Keyinroq istalgan vaqtda o'zgartirishingiz mumkin.",
      note: "Pullik tariflar uchun hisob-faktura yuboriladi. To'lov tasdiqlangach tarif faollashadi.",
      choose: "Tanlash",
      choosing: "To'lovga yo'naltirilmoqda…",
      checkoutFailedTitle: "To'lovni boshlab bo'lmadi",
      checkoutFailedBody: "Hech qanday summa yechilmadi. Qaytadan urinib ko'ring yoki boshqa tarifni tanlang.",
      retry: "Qaytadan urinish"
    },
    photos: {
      title: "Biznesingiz rasmlari",
      subtitle: "O'zingiz yuklagan rasmlar darhol ko'rinadi va asosiy rasm sifatida tanlanishi mumkin.",
      uploadLabel: "Rasm yuklash",
      makeCover: "Asosiy rasm qilish",
      isCoverLabel: "Asosiy rasm",
      pendingLabel: "Ko'rib chiqilmoqda",
      empty: "Hozircha rasm yo'q.",
      skip: "Hozircha o'tkazib yuborish",
      continueCta: "Boshqaruv paneliga o'tish"
    },
    analytics: {
      title: "Tahlil",
      subtitle: "Mijozlar sizni qanday topayotgani va nima qilayotgani.",
      window: "Oxirgi 30 kun",
      visits: "Tashriflar",
      unique: "Noyob mehmonlar",
      rating: "O'rtacha reyting",
      revenue: "Tushum",
      visitTrend: "Tashriflar dinamikasi",
      funnel: "Mijoz harakatlari",
      ratingTrend: "Reyting dinamikasi",
      bookings: "Bandlovlar",
      noData: "Hozircha ma'lumot yo'q. Ma'lumot tashriflar boshlangach paydo bo'ladi.",
      ofViews: "ko'rishlardan",
      upgradeTitle: "Tahlil Pro tarifida",
      upgradeText: "Tashriflar, mijoz harakatlari va reyting dinamikasini ko'rish uchun tarifni oshiring.",
      upgradeCta: "Tariflarni ko'rish",
      eventView: "Sahifa ko'rildi",
      eventPhoto: "Rasm ko'rildi",
      eventDirections: "Yo'nalish",
      eventCall: "Qo'ng'iroq",
      eventMessage: "Xabar"
    },
    customers: {
      title: "Mijozlar",
      subtitle: "Bandlovlardan avtomatik yig'ilgan mijozlar ro'yxati.",
      empty: "Hozircha mijozlar yo'q. Birinchi bandlov qabul qilinganda bu yerda paydo bo'ladi.",
      colName: "Ism / Telefon",
      colLastVisit: "Oxirgi tashrif",
      colVisits: "Tashriflar",
      colSpend: "Jami xarajat",
      colTags: "Teglar",
      colConsent: "Marketingga rozilik",
      consentYes: "Ha",
      consentNo: "Yo'q",
      never: "Hech qachon"
    },
    customerDetail: {
      back: "Mijozlar ro'yxatiga qaytish",
      notFound: "Mijoz topilmadi",
      firstSeen: "Birinchi marta",
      profile: "Mijoz ma'lumotlari",
      bookings: "Bandlovlar",
      reviews: "Sharhlar",
      visits: "Tashriflar tarixi",
      noBookings: "Bandlovlar yo'q",
      noReviews: "Sharhlar yo'q",
      noVisits: "Tashriflar qayd etilmagan",
      noAccountHint: "Bu mijoz Manzil hisobiga ulanmagan, shuning uchun sharhlari ko'rsatilmaydi.",
      colService: "Xizmat",
      colDate: "Sana",
      colStatus: "Holat",
      colAmount: "Summa",
      notes: "Izohlar",
      noNotes: "Izoh yo'q"
    },
    terms: {
      section: "Shartlar va shartnoma",
      hint: "Ro'yxatdan o'tish uchun foydalanish shartlarini qabul qilishingiz kerak.",
      checkbox: "Men foydalanish shartlari va ommaviy oferta shartnomasini o'qib chiqdim va qabul qilaman",
      read: "Shartlarni o'qish",
      version: "Versiya",
      unavailable: "Shartlar hujjati hali chop etilmagan. Ro'yxatdan o'tish davom etadi, ammo qabul qilish yozuvi saqlanmaydi.",
      contractTitle: "Sizning shartnomangiz",
      contractNo: "Shartnoma raqami",
      download: "Shartnomani yuklab olish",
      noContract: "Shartnoma hali yaratilmagan.",
      accepted: "Qabul qilingan hujjatlar"
    },
    common: {
      signInPrompt: "Kabinet uchun tizimga kiring",
      noBusiness: "Sizda hali biznes yo'q",
      noBusinessText: "Yangi biznes qo'shing yoki mavjud listingni tasdiqlang.",
      registerCta: "Biznes qo'shish",
      switchBusiness: "Biznes"
    },
    admin: {
      accessRestricted: "Kirish cheklangan",
      accessRestrictedText:
        "Bu konsol faqat administrator hisoblari uchun ochiq. Davom etish uchun administrator hisobi bilan tizimga kiring.",
      signIn: "Kirish",
      kicker: "Admin konsoli",
      title: "Platforma boshqaruv markazi",
      subtitle: "Kompaniyalar navbati, kontent moderatsiyasi va bildirishnomalar — barchasi shu yerda.",
      statBusinesses: "Database listinglari",
      statPendingClaims: "Pending claimlar",
      statReviews: "Sharhlar",
      statCategories: "Kategoriyalar",
      statModerationQueue: "Moderatsiya navbati",
      claimsKicker: "Claim navbati",
      claimsTitle: "Kutilayotgan biznes claimlar",
      claimsSubtitle: "Adminlar claimlarni tekshiradi, tasdiqlaydi yoki rad etadi.",
      colBusiness: "Biznes",
      colRequester: "So'rovchi",
      colNote: "Izoh",
      colActions: "Amallar",
      approve: "Tasdiqlash",
      reject: "Rad etish",
      claimsEmpty: "Hozircha pending claimlar yo'q.",
      reportsKicker: "Moderatsiya navbati",
      reportsTitle: "Ochiq shikoyatlar",
      reportsSubtitle: "Shikoyat qilingan sharhlar va rasmlarni shu yerda hal qilish yoki rad etish mumkin.",
      colType: "Turi",
      colReason: "Sababi",
      colReporter: "Shikoyatchi",
      colDetail: "Tafsilot",
      typeReview: "Shikoyat qilingan sharh",
      typePhoto: "Shikoyat qilingan rasm",
      removeContent: "Kontentni o'chirish",
      dismissReport: "Shikoyatni rad etish",
      reportsEmpty: "Ochiq moderatsiya shikoyatlari yo'q.",

      nav: {
        overview: "Umumiy ko'rinish",
        companies: "Kompaniyalar",
        notifications: "Bildirishnomalar",
        notificationsUnread: "Bildirishnomalar ({n})",
        roleFallback: "Admin"
      },
      common: {
        permissionDeniedTitle: "Ruxsat yo'q",
        permissionDeniedText: "Bu bo'limni ko'rish uchun kerakli ruxsatingiz yo'q.",
        reasonLabel: "Sabab",
        reasonHint: "Kamida 10 belgi",
        viewDetail: "Batafsil",
        statusUnclaimed: "Da'vo qilinmagan",
        statusPendingClaim: "Tasdiq kutilmoqda",
        statusClaimed: "Tasdiqlangan",
        statusSuspended: "To'xtatilgan",
        moderationPending: "Kutilmoqda",
        moderationApproved: "Tasdiqlangan",
        moderationRejected: "Rad etilgan"
      },
      overviewPage: {
        statsTitle: "Platforma holati",
        statPendingBusinesses: "Tasdiq kutayotgan kompaniyalar",
        statFlaggedReviews: "Shikoyat qilingan sharhlar",
        statBannedUsers: "Bloklangan foydalanuvchilar",
        statAdmins: "Faol adminlar",
        noAnalyticsPermission: "Statistikani ko'rish uchun ruxsatingiz yo'q.",
        inboxTitle: "O'qilmagan bildirishnomalar",
        inboxSubtitle: "Har bir yozuv tegishli kompaniyaga olib boradi.",
        inboxEmptyTitle: "Navbat bo'sh",
        inboxEmptyText: "Yangi kompaniya tasdiq kutganda, sharh shikoyat qilinganda yoki rasm/shartnoma ko'rib chiqishni kutganda shu yerda paydo bo'ladi.",
        markAllRead: "Barchasini o'qilgan deb belgilash",
        markingAll: "Belgilanmoqda…",
        viewAll: "Barcha bildirishnomalar",
        noNotificationPermission: "Bildirishnomalarni ko'rish uchun ruxsatingiz yo'q.",
        nothingTitle: "Ko'rsatadigan narsa yo'q",
        nothingText: "Hisobingizga hali konsol ruxsatlari biriktirilmagan. Administratordan ruxsat so'rang."
      },
      companiesPage: {
        title: "Kompaniyalar",
        subtitle: "Qidiring, holat bo'yicha saralang, tasdiqlang yoki rad eting.",
        searchPlaceholder: "Nomi, manzili yoki tumani bo'yicha qidirish",
        searchSubmit: "Qidirish",
        filterAll: "Barchasi",
        colName: "Kompaniya",
        colCategory: "Kategoriya",
        colLocation: "Joylashuv",
        colPhone: "Telefon",
        colRating: "Baho",
        colOwner: "Egasi",
        colCreated: "Yaratilgan",
        colStatus: "Holat",
        colActions: "Amallar",
        noOwner: "Egasi yo'q",
        approve: "Tasdiqlash",
        approving: "Tasdiqlanmoqda…",
        reject: "Rad etish",
        rejecting: "Rad etilmoqda…",
        reasonPlaceholder: "Rad etish sababi (kamida 10 belgi)",
        emptyTitle: "Kompaniyalar topilmadi",
        emptyText: "Qidiruv yoki holat filtriga mos kompaniya yo'q. Filtrni tozalab ko'ring.",
        view: "Ochish"
      },
      companyTabs: {
        overview: "Umumiy",
        consumers: "Mijozlar",
        reviews: "Sharhlar",
        photos: "Rasmlar",
        contracts: "Shartnomalar",
        audit: "Tarix"
      },
      companyDetail: {
        notFoundTitle: "Kompaniya topilmadi",
        notFoundText: "Bu kompaniya mavjud emas yoki uni ko'rish uchun ruxsatingiz yo'q.",
        backToList: "Kompaniyalar ro'yxatiga qaytish",
        owner: "Egasi",
        noOwner: "Hali da'vo qilinmagan",
        category: "Kategoriya",
        createdAt: "Yaratilgan sana",
        claimedAt: "Tasdiqlangan sana",
        neverClaimed: "Hali tasdiqlanmagan",
        rating: "Baho",
        reviewsCount: "sharh",
        plan: "Tarif",
        planStatus: "Obuna holati",
        planRenews: "Keyingi to'lov",
        noSubscription: "Obuna yo'q (bepul tarif)",
        featured: "Vitrinada",
        featureOn: "Ha",
        featureOff: "Yo'q",
        featuringOn: "Vitrinaga qo'shish",
        featuringOff: "Vitrinadan olib tashlash",
        approve: "Kompaniyani tasdiqlash",
        approving: "Tasdiqlanmoqda…",
        reject: "Kompaniyani rad etish",
        rejecting: "Rad etilmoqda…",
        editTitle: "Ma'lumotlarni tahrirlash",
        editHint: "Faqat to'ldirilgan maydonlar saqlanadi.",
        editName: "Nomi",
        editAddress: "Manzil",
        editDistrict: "Tuman",
        editPhone: "Telefon",
        editEmail: "Email",
        editWebsite: "Veb-sayt",
        editPriceTier: "Narx darajasi",
        editSubmit: "Saqlash",
        editSubmitting: "Saqlanmoqda…",
        activityTitle: "Faollik",
        activityVisits: "Tashriflar",
        activityBookings: "Bandlovlar",
        activityReviews: "Tasdiqlangan sharhlar",
        activityCustomers: "Mijozlar"
      },
      consumersTab: {
        title: "Mijozlar",
        subtitle: "Ushbu kompaniyaning mijozlari va sharh muallifllari, bitta ro'yxatda.",
        emptyTitle: "Mijozlar yo'q",
        emptyText: "Bandlov qabul qilinganda yoki sharh yozilganda mijoz shu yerda paydo bo'ladi.",
        colName: "Ism",
        colContact: "Aloqa",
        colSource: "Manba",
        colVisits: "Tashriflar",
        colSpend: "Jami xarajat",
        colLastVisit: "Oxirgi tashrif",
        colReviews: "Sharhlar",
        sourceCustomer: "Mijoz",
        sourceReviewer: "Sharh muallifi",
        sourceBoth: "Mijoz + sharh muallifi"
      },
      reviewsTab: {
        title: "Sharhlar",
        subtitle: "Ushbu kompaniyaga yozilgan sharhlarni moderatsiya qiling.",
        emptyTitle: "Sharhlar yo'q",
        emptyText: "Bu kompaniyaga hali sharh yozilmagan.",
        colAuthor: "Muallif",
        colRating: "Baho",
        colText: "Matn",
        colStatus: "Holat",
        colReported: "Shikoyatlar",
        colDate: "Sana",
        colActions: "Amallar",
        approve: "Tasdiqlash",
        approving: "Tasdiqlanmoqda…",
        reject: "Rad etish",
        rejecting: "Rad etilmoqda…",
        remove: "O'chirish",
        removing: "O'chirilmoqda…",
        reasonPlaceholder: "Sabab (kamida 10 belgi)"
      },
      photosTab: {
        title: "Rasmlar",
        subtitle: "Ko'rib chiqilishi kerak bo'lgan rasmlar.",
        emptyTitle: "Ko'rib chiqiladigan rasm yo'q",
        emptyText: "Yangi yuklangan rasmlar shu yerda ko'rinadi.",
        fromReview: "Sharhdan yuklangan",
        approve: "Tasdiqlash",
        approving: "Tasdiqlanmoqda…",
        reject: "Rad etish",
        rejecting: "Rad etilmoqda…",
        reasonPlaceholder: "Rad etish sababi (kamida 10 belgi)"
      },
      contractsTab: {
        title: "Shartnomalar",
        subtitle: "Ushbu kompaniyaning shartnomasi va qabul qilingan hujjatlar.",
        contractNo: "Shartnoma raqami",
        contractVersion: "Shablon versiyasi",
        contractGenerated: "Yaratilgan sana",
        noContract: "Bu kompaniya uchun shartnoma hali yaratilmagan.",
        acceptancesTitle: "Qabul qilingan hujjatlar",
        acceptancesEmpty: "Hech qanday hujjat qabul qilinmagan.",
        legalDocsTitle: "Global huquqiy hujjatlar",
        legalDocsEmpty: "Hali hech qanday hujjat chop etilmagan.",
        colKind: "Turi",
        colVersion: "Versiya",
        colLocale: "Til",
        colPublished: "Chop etilgan",
        colAcceptances: "Qabullar",
        publishTitle: "Yangi versiya chop etish",
        publishHint: "Qabul qilishlar aniq versiyaga bog'lanadi — mavjud matn tahrirlanmaydi, faqat yangi versiya chop etiladi.",
        publishKind: "Hujjat turi",
        publishVersion: "Versiya",
        publishLocale: "Til",
        publishDocTitle: "Sarlavha",
        publishBody: "Matn",
        publishSubmit: "Chop etish",
        publishSubmitting: "Chop etilmoqda…",
        kindTerms: "Foydalanish shartlari",
        kindPrivacy: "Maxfiylik siyosati",
        kindContract: "Shartnoma shabloni"
      },
      auditTab: {
        title: "Tarix",
        subtitle: "Ushbu kompaniya bo'yicha barcha admin amallari.",
        emptyTitle: "Tarix bo'sh",
        emptyText: "Bu kompaniya bo'yicha hali hech qanday admin amali qayd etilmagan.",
        colWhen: "Vaqti",
        colActor: "Admin",
        colAction: "Amal",
        colReason: "Sabab",
        colTarget: "Obyekt"
      },
      notificationsPage: {
        title: "Bildirishnomalar",
        subtitle: "Insonning e'tiborini talab qiladigan barcha hodisalar.",
        filterAll: "Barchasi",
        filterUnread: "O'qilmagan",
        markAllRead: "Barchasini o'qilgan deb belgilash",
        markingAll: "Belgilanmoqda…",
        markRead: "O'qilgan deb belgilash",
        markingRead: "Belgilanmoqda…",
        colKind: "Turi",
        colTitle: "Sarlavha",
        colBusiness: "Kompaniya",
        colCreated: "Vaqti",
        colStatus: "Holat",
        colActions: "Amallar",
        statusUnread: "O'qilmagan",
        statusRead: "O'qilgan",
        emptyTitle: "Bildirishnoma yo'q",
        emptyText: "Yangi kompaniya tasdiq kutganda, sharh shikoyat qilinganda yoki rasm/shartnoma ko'rib chiqishni kutganda shu yerda paydo bo'ladi.",
        kindBusinessAwaitingApproval: "Kompaniya tasdiq kutmoqda",
        kindReviewReported: "Sharhga shikoyat qilindi",
        kindPhotoPending: "Rasm ko'rib chiqilishi kerak",
        kindContractPending: "Shartnoma chop etilishi kerak",
        noBusinessLink: "—"
      },
      loginPage: {
        title: "Admin konsoliga kirish",
        subtitle: "Faqat login va parol bilan kirish mumkin.",
        usernameLabel: "Login",
        passwordLabel: "Parol",
        submit: "Kirish",
        submitting: "Kirilmoqda…",
        errorGeneric: "Login yoki parol noto'g'ri."
      },
      dataPage: {
        title: "Ma'lumotlar bazasi",
        subtitle: "Faqat o'qish uchun: jadvallar, qatorlar soni va saqlash hajmi.",
        tablesTitle: "Jadvallar",
        colTable: "Jadval",
        colRows: "Qatorlar",
        viewTable: "Ko'rish",
        storageTitle: "Saqlash (Storage)",
        storageSubtitle: "Bucketlar, obyektlar soni va umumiy hajm.",
        storageNotConfigured: "Supabase Storage sozlanmagan.",
        colBucket: "Bucket",
        colObjects: "Obyektlar",
        colBytes: "Hajmi",
        bucketPublic: "Ochiq",
        bucketPrivate: "Yopiq",
        backToTables: "Jadvallar ro'yxatiga qaytish",
        tableRowsTitle: "Qatorlar",
        rowsEmptyTitle: "Qatorlar yo'q",
        rowsEmptyText: "Bu jadvalda hozircha hech qanday yozuv yo'q.",
        limitLabel: "Sahifadagi qatorlar",
        prevPage: "Oldingi",
        nextPage: "Keyingi",
        totalRowsLabel: "Jami",
        truncatedNotice: "Hajm katta bo'lgani uchun hisoblash to'liq emas — bu pastki chegara.",
        redactedNotice: "Maxfiy ustunlar (parol, email, telefon va h.k.) niqoblangan."
      }
    }
  },
  ru: {
    menu: {
      section: "Основное меню",
      overview: "Панель управления",
      bookings: "Брони",
      announcements: "Объявления",
      packages: "Услуги и цены",
      reviews: "Отзывы",
      analytics: "Аналитика",
      customers: "Клиенты",
      settings: "Настройки",
      plan: "Тариф",
      upgrade: "Повысить тариф",
      viewPublic: "Открытая страница",
      partnerPortal: "Портал партнёров",
      mobileMenu: "Меню"
    },
    overview: {
      title: "Панель управления",
      visits30: "Визиты (30 дней)",
      unique30: "Уникальные гости",
      reviewsTotal: "Всего отзывов",
      avgRating: "Средняя оценка",
      vsNote: "за последние 30 дней",
      last7: "за последние 7 дней",
      visitsChart: "Визиты по дням",
      ratingDist: "Распределение оценок",
      completeness: "Заполненность профиля",
      completenessHint: "Полный профиль выше показывается в поиске.",
      published: "Опубликованные объявления",
      activePackages: "Активные услуги",
      pendingNote: "Бизнес ожидает подтверждения администратора. После проверки профиль станет публичным.",
      welcome: "С возвращением! Вот что происходит с вашим бизнесом сегодня.",
      totalBookings: "Всего броней",
      revenue: "Выручка",
      activeDiscounts: "Активные скидки",
      businessHealth: "Состояние бизнеса",
      rangeWeek: "Неделя",
      rangeMonth: "Месяц",
      recentBookings: "Последние брони",
      viewAll: "Смотреть все",
      statusClaimed: "Подтверждён",
      statusPending: "Ожидает подтверждения"
    },
    bookings: {
      title: "Брони",
      subtitle: "Записывайте сюда брони, принятые по телефону или лично.",
      newTitle: "Новая бронь",
      customerPhone: "Телефон клиента",
      serviceName: "Услуга",
      startsAt: "Время начала",
      endsAt: "Время окончания (необязательно)",
      depositAmount: "Депозит, сум (необязательно)",
      submit: "Добавить бронь",
      submitting: "Сохраняем…",
      upcoming: "Предстоящие",
      filterAll: "Все",
      table: {
        customer: "Клиент",
        phone: "Телефон",
        service: "Услуга",
        when: "Время",
        status: "Статус",
        actions: "Действия"
      },
      statuses: {
        pending: "Ожидает",
        confirmed: "Подтверждена",
        canceled: "Отменена",
        completed: "Выполнена",
        no_show: "Не пришёл"
      },
      confirm: "Подтвердить",
      confirming: "Подтверждаем…",
      complete: "Отметить выполненной",
      completing: "Отмечаем…",
      cancel: "Отменить",
      canceling: "Отменяем…",
      noShow: "Отметить неявку",
      noShowing: "Отмечаем…",
      emptyTitle: "Пока нет броней",
      emptyBody:
        "Записывайте сюда брони, когда клиент звонит или приходит лично. Когда бронь отмечена «Выполнена», клиент автоматически появляется в списке клиентов, а после отзыва получает отметку «подтверждённый визит».",
      noEndsAt: "—"
    },
    announcements: {
      title: "Объявления",
      subtitle: "Публикуйте новости, скидки и сообщения.",
      newTitle: "Новое объявление",
      kind: "Тип",
      kinds: { news: "Новость", discount: "Скидка", broadcast: "Сообщение" },
      formTitle: "Заголовок",
      formBody: "Текст",
      discountPercent: "Скидка (%)",
      startsAt: "Дата начала",
      endsAt: "Дата окончания",
      submit: "Опубликовать",
      saveDraft: "Сохранить как черновик",
      statuses: { draft: "Черновик", published: "Опубликовано", archived: "Архив" },
      publish: "Опубликовать",
      archive: "В архив",
      remove: "Удалить",
      empty: "Объявлений пока нет.",
      table: { title: "Заголовок", kind: "Тип", status: "Статус", date: "Дата", actions: "Действия" }
    },
    packages: {
      title: "Услуги и цены",
      subtitle: "Список услуг виден клиентам на открытой странице.",
      newTitle: "Новая услуга",
      name: "Название",
      description: "Описание",
      price: "Цена (сум)",
      submit: "Добавить",
      activate: "Активировать",
      deactivate: "Остановить",
      remove: "Удалить",
      empty: "Услуг пока нет.",
      table: { name: "Услуга", price: "Цена", status: "Статус", actions: "Действия" },
      active: "Активна",
      inactive: "Неактивна"
    },
    reviews: {
      title: "Отзывы",
      subtitle: "Официально отвечайте на отзывы клиентов.",
      empty: "Отзывов пока нет.",
      reply: "Ответить",
      replyPlaceholder: "Текст официального ответа",
      send: "Отправить",
      replied: "Ответ отправлен",
      exportCsv: "Скачать CSV"
    },
    settings: {
      title: "Настройки",
      subtitle: "Данные бизнеса видны на открытой странице.",
      profile: "Данные бизнеса",
      name: "Название",
      legalName: "Юридическое название",
      taxId: "ИНН/СТИР (9 цифр)",
      address: "Адрес",
      district: "Район",
      phone: "Телефон",
      email: "Email",
      website: "Сайт",
      instagram: "Instagram",
      telegram: "Telegram",
      hours: "Часы работы",
      description: "Описание",
      save: "Сохранить",
      subscription: "Подписка",
      plan: "Тариф",
      status: "Статус",
      renews: "Следующий платёж",
      subStatuses: {
        active: "Активна",
        trial: "Пробный период",
        invoice_pending: "Ожидает оплаты",
        canceled: "Отменена"
      }
    },
    register: {
      title: "Регистрация бизнеса",
      subtitle:
        "Заполните данные. Заявку проверит администратор, после подтверждения кабинет откроется полностью.",
      basics: "Основные данные",
      category: "Категория",
      contactSection: "Контакты",
      legalSection: "Юридические данные (Узбекистан)",
      legalHint: "ИНН необязателен, но ускоряет подтверждение.",
      submit: "Зарегистрировать",
      submitting: "Отправляем…",
      failedTitle: "Не удалось зарегистрировать",
      failedBody: "Данные не сохранены. Попробуйте ещё раз — дубликат бизнеса не создастся.",
      retry: "Повторить",
      signInFirst: "Сначала войдите",
      signInText: "Для регистрации бизнеса требуется аккаунт.",
      signIn: "Войти",
      brandWordmark: "Manzil для бизнеса",
      brandTagline: "Развивайте свой локальный бизнес.",
      brandSubline:
        "Создайте профиль в Manzil — клиенты найдут вас, оставят отзывы и свяжутся с вами.",
      mobileKicker: "Регистрация в портале для партнёров",
      namePlaceholder: "Например: Chinor Kafe",
      categoryPlaceholder: "Выберите категорию",
      signUpPrompt: "Ещё нет аккаунта?",
      signUpCta: "Зарегистрироваться"
    },
    plans: {
      title: "Выберите тариф",
      subtitle: "Его можно изменить в любой момент.",
      note: "Для платных тарифов выставляется счёт. Тариф активируется после подтверждения оплаты.",
      choose: "Выбрать",
      choosing: "Переходим к оплате…",
      checkoutFailedTitle: "Не удалось начать оплату",
      checkoutFailedBody: "Списания не произошло. Попробуйте ещё раз или выберите другой тариф.",
      retry: "Повторить"
    },
    photos: {
      title: "Фотографии бизнеса",
      subtitle: "Загруженные вами фото видны сразу и могут быть выбраны как обложка.",
      uploadLabel: "Загрузить фото",
      makeCover: "Сделать обложкой",
      isCoverLabel: "Обложка",
      pendingLabel: "На проверке",
      empty: "Фотографий пока нет.",
      skip: "Пропустить пока что",
      continueCta: "Перейти в панель управления"
    },
    analytics: {
      title: "Аналитика",
      subtitle: "Как клиенты находят вас и что делают дальше.",
      window: "Последние 30 дней",
      visits: "Визиты",
      unique: "Уникальные посетители",
      rating: "Средний рейтинг",
      revenue: "Выручка",
      visitTrend: "Динамика визитов",
      funnel: "Действия клиентов",
      ratingTrend: "Динамика рейтинга",
      bookings: "Брони",
      noData: "Пока нет данных. Они появятся, когда начнутся визиты.",
      ofViews: "от просмотров",
      upgradeTitle: "Аналитика на тарифе Pro",
      upgradeText: "Повысьте тариф, чтобы видеть визиты, действия клиентов и динамику рейтинга.",
      upgradeCta: "Посмотреть тарифы",
      eventView: "Просмотр страницы",
      eventPhoto: "Просмотр фото",
      eventDirections: "Маршрут",
      eventCall: "Звонок",
      eventMessage: "Сообщение"
    },
    customers: {
      title: "Клиенты",
      subtitle: "Список клиентов, автоматически собранный из броней.",
      empty: "Пока нет клиентов. Появятся здесь после первой принятой брони.",
      colName: "Имя / Телефон",
      colLastVisit: "Последний визит",
      colVisits: "Визиты",
      colSpend: "Всего потрачено",
      colTags: "Теги",
      colConsent: "Согласие на маркетинг",
      consentYes: "Да",
      consentNo: "Нет",
      never: "Никогда"
    },
    customerDetail: {
      back: "Назад к списку клиентов",
      notFound: "Клиент не найден",
      firstSeen: "Первый визит",
      profile: "Данные клиента",
      bookings: "Брони",
      reviews: "Отзывы",
      visits: "История визитов",
      noBookings: "Броней нет",
      noReviews: "Отзывов нет",
      noVisits: "Визиты не зафиксированы",
      noAccountHint: "Клиент не связан с аккаунтом Manzil, поэтому отзывы не отображаются.",
      colService: "Услуга",
      colDate: "Дата",
      colStatus: "Статус",
      colAmount: "Сумма",
      notes: "Заметки",
      noNotes: "Заметок нет"
    },
    terms: {
      section: "Условия и договор",
      hint: "Для регистрации необходимо принять условия использования.",
      checkbox: "Я прочитал(а) и принимаю условия использования и договор публичной оферты",
      read: "Прочитать условия",
      version: "Версия",
      unavailable: "Документ с условиями ещё не опубликован. Регистрация продолжится, но запись о принятии не будет сохранена.",
      contractTitle: "Ваш договор",
      contractNo: "Номер договора",
      download: "Скачать договор",
      noContract: "Договор ещё не сформирован.",
      accepted: "Принятые документы"
    },
    common: {
      signInPrompt: "Войдите, чтобы открыть кабинет",
      noBusiness: "У вас пока нет бизнеса",
      noBusinessText: "Добавьте новый бизнес или подтвердите существующий листинг.",
      registerCta: "Добавить бизнес",
      switchBusiness: "Бизнес"
    },
    admin: {
      accessRestricted: "Доступ ограничен",
      accessRestrictedText:
        "Эта консоль доступна только администраторам. Войдите под учётной записью администратора, чтобы продолжить.",
      signIn: "Войти",
      kicker: "Админ-консоль",
      title: "Центр управления платформой",
      subtitle: "Очередь компаний, модерация контента и уведомления — всё в одном месте.",
      statBusinesses: "Записи в базе",
      statPendingClaims: "Заявки на рассмотрении",
      statReviews: "Отзывы",
      statCategories: "Категории",
      statModerationQueue: "Очередь модерации",
      claimsKicker: "Очередь заявок",
      claimsTitle: "Заявки на подтверждение бизнеса",
      claimsSubtitle: "Администраторы проверяют, подтверждают или отклоняют заявки.",
      colBusiness: "Бизнес",
      colRequester: "Заявитель",
      colNote: "Заметка",
      colActions: "Действия",
      approve: "Подтвердить",
      reject: "Отклонить",
      claimsEmpty: "Пока нет заявок на рассмотрении.",
      reportsKicker: "Очередь модерации",
      reportsTitle: "Открытые жалобы",
      reportsSubtitle: "Здесь можно рассмотреть или отклонить жалобы на отзывы и фото.",
      colType: "Тип",
      colReason: "Причина",
      colReporter: "Заявитель",
      colDetail: "Детали",
      typeReview: "Жалоба на отзыв",
      typePhoto: "Жалоба на фото",
      removeContent: "Удалить контент",
      dismissReport: "Отклонить жалобу",
      reportsEmpty: "Открытых жалоб модерации нет.",

      nav: {
        overview: "Обзор",
        companies: "Компании",
        notifications: "Уведомления",
        notificationsUnread: "Уведомления ({n})",
        roleFallback: "Админ"
      },
      common: {
        permissionDeniedTitle: "Нет доступа",
        permissionDeniedText: "У вас нет разрешения для просмотра этого раздела.",
        reasonLabel: "Причина",
        reasonHint: "Минимум 10 символов",
        viewDetail: "Подробнее",
        statusUnclaimed: "Не заявлен",
        statusPendingClaim: "Ожидает подтверждения",
        statusClaimed: "Подтверждён",
        statusSuspended: "Приостановлен",
        moderationPending: "Ожидает",
        moderationApproved: "Одобрено",
        moderationRejected: "Отклонено"
      },
      overviewPage: {
        statsTitle: "Состояние платформы",
        statPendingBusinesses: "Компании на рассмотрении",
        statFlaggedReviews: "Отзывы с жалобами",
        statBannedUsers: "Заблокированные пользователи",
        statAdmins: "Активные админы",
        noAnalyticsPermission: "У вас нет разрешения на просмотр статистики.",
        inboxTitle: "Непрочитанные уведомления",
        inboxSubtitle: "Каждая запись ведёт к соответствующей компании.",
        inboxEmptyTitle: "Очередь пуста",
        inboxEmptyText: "Здесь появится запись, когда новая компания будет ждать подтверждения, поступит жалоба на отзыв, или фото/договор будут ждать проверки.",
        markAllRead: "Отметить всё прочитанным",
        markingAll: "Отмечаем…",
        viewAll: "Все уведомления",
        noNotificationPermission: "У вас нет разрешения на просмотр уведомлений.",
        nothingTitle: "Показывать нечего",
        nothingText: "Вашему аккаунту пока не назначены разрешения консоли. Обратитесь к администратору."
      },
      companiesPage: {
        title: "Компании",
        subtitle: "Ищите, фильтруйте по статусу, подтверждайте или отклоняйте.",
        searchPlaceholder: "Поиск по названию, адресу или району",
        searchSubmit: "Искать",
        filterAll: "Все",
        colName: "Компания",
        colCategory: "Категория",
        colLocation: "Расположение",
        colPhone: "Телефон",
        colRating: "Рейтинг",
        colOwner: "Владелец",
        colCreated: "Создана",
        colStatus: "Статус",
        colActions: "Действия",
        noOwner: "Нет владельца",
        approve: "Подтвердить",
        approving: "Подтверждаем…",
        reject: "Отклонить",
        rejecting: "Отклоняем…",
        reasonPlaceholder: "Причина отклонения (минимум 10 символов)",
        emptyTitle: "Компании не найдены",
        emptyText: "Нет компаний, соответствующих поиску или фильтру статуса. Попробуйте сбросить фильтр.",
        view: "Открыть"
      },
      companyTabs: {
        overview: "Обзор",
        consumers: "Клиенты",
        reviews: "Отзывы",
        photos: "Фото",
        contracts: "Договоры",
        audit: "История"
      },
      companyDetail: {
        notFoundTitle: "Компания не найдена",
        notFoundText: "Этой компании не существует, или у вас нет разрешения на её просмотр.",
        backToList: "Назад к списку компаний",
        owner: "Владелец",
        noOwner: "Ещё не подтверждён",
        category: "Категория",
        createdAt: "Дата создания",
        claimedAt: "Дата подтверждения",
        neverClaimed: "Ещё не подтверждена",
        rating: "Рейтинг",
        reviewsCount: "отзывов",
        plan: "Тариф",
        planStatus: "Статус подписки",
        planRenews: "Следующий платёж",
        noSubscription: "Подписки нет (бесплатный тариф)",
        featured: "В подборке",
        featureOn: "Да",
        featureOff: "Нет",
        featuringOn: "Добавить в подборку",
        featuringOff: "Убрать из подборки",
        approve: "Подтвердить компанию",
        approving: "Подтверждаем…",
        reject: "Отклонить компанию",
        rejecting: "Отклоняем…",
        editTitle: "Редактировать данные",
        editHint: "Сохранятся только заполненные поля.",
        editName: "Название",
        editAddress: "Адрес",
        editDistrict: "Район",
        editPhone: "Телефон",
        editEmail: "Email",
        editWebsite: "Сайт",
        editPriceTier: "Ценовой уровень",
        editSubmit: "Сохранить",
        editSubmitting: "Сохраняем…",
        activityTitle: "Активность",
        activityVisits: "Визиты",
        activityBookings: "Брони",
        activityReviews: "Подтверждённые отзывы",
        activityCustomers: "Клиенты"
      },
      consumersTab: {
        title: "Клиенты",
        subtitle: "Клиенты и авторы отзывов этой компании в одном списке.",
        emptyTitle: "Клиентов нет",
        emptyText: "Клиент появится здесь после принятой брони или оставленного отзыва.",
        colName: "Имя",
        colContact: "Контакт",
        colSource: "Источник",
        colVisits: "Визиты",
        colSpend: "Всего потрачено",
        colLastVisit: "Последний визит",
        colReviews: "Отзывы",
        sourceCustomer: "Клиент",
        sourceReviewer: "Автор отзыва",
        sourceBoth: "Клиент + автор отзыва"
      },
      reviewsTab: {
        title: "Отзывы",
        subtitle: "Модерируйте отзывы, оставленные этой компании.",
        emptyTitle: "Отзывов нет",
        emptyText: "Этой компании ещё не оставили ни одного отзыва.",
        colAuthor: "Автор",
        colRating: "Оценка",
        colText: "Текст",
        colStatus: "Статус",
        colReported: "Жалобы",
        colDate: "Дата",
        colActions: "Действия",
        approve: "Подтвердить",
        approving: "Подтверждаем…",
        reject: "Отклонить",
        rejecting: "Отклоняем…",
        remove: "Удалить",
        removing: "Удаляем…",
        reasonPlaceholder: "Причина (минимум 10 символов)"
      },
      photosTab: {
        title: "Фото",
        subtitle: "Фотографии, ожидающие проверки.",
        emptyTitle: "Нет фото на проверке",
        emptyText: "Здесь появятся недавно загруженные фотографии.",
        fromReview: "Загружено вместе с отзывом",
        approve: "Одобрить",
        approving: "Одобряем…",
        reject: "Отклонить",
        rejecting: "Отклоняем…",
        reasonPlaceholder: "Причина отклонения (минимум 10 символов)"
      },
      contractsTab: {
        title: "Договоры",
        subtitle: "Договор этой компании и принятые документы.",
        contractNo: "Номер договора",
        contractVersion: "Версия шаблона",
        contractGenerated: "Дата создания",
        noContract: "Для этой компании договор ещё не сформирован.",
        acceptancesTitle: "Принятые документы",
        acceptancesEmpty: "Ни один документ не был принят.",
        legalDocsTitle: "Глобальные юридические документы",
        legalDocsEmpty: "Пока ни один документ не опубликован.",
        colKind: "Тип",
        colVersion: "Версия",
        colLocale: "Язык",
        colPublished: "Опубликован",
        colAcceptances: "Принятий",
        publishTitle: "Опубликовать новую версию",
        publishHint: "Принятия привязаны к точной версии — текст не редактируется, публикуется только новая версия.",
        publishKind: "Тип документа",
        publishVersion: "Версия",
        publishLocale: "Язык",
        publishDocTitle: "Заголовок",
        publishBody: "Текст",
        publishSubmit: "Опубликовать",
        publishSubmitting: "Публикуем…",
        kindTerms: "Условия использования",
        kindPrivacy: "Политика конфиденциальности",
        kindContract: "Шаблон договора"
      },
      auditTab: {
        title: "История",
        subtitle: "Все административные действия по этой компании.",
        emptyTitle: "История пуста",
        emptyText: "По этой компании ещё не зафиксировано ни одного административного действия.",
        colWhen: "Время",
        colActor: "Админ",
        colAction: "Действие",
        colReason: "Причина",
        colTarget: "Объект"
      },
      notificationsPage: {
        title: "Уведомления",
        subtitle: "Все события, требующие внимания человека.",
        filterAll: "Все",
        filterUnread: "Непрочитанные",
        markAllRead: "Отметить всё прочитанным",
        markingAll: "Отмечаем…",
        markRead: "Отметить прочитанным",
        markingRead: "Отмечаем…",
        colKind: "Тип",
        colTitle: "Заголовок",
        colBusiness: "Компания",
        colCreated: "Время",
        colStatus: "Статус",
        colActions: "Действия",
        statusUnread: "Непрочитано",
        statusRead: "Прочитано",
        emptyTitle: "Уведомлений нет",
        emptyText: "Здесь появится запись, когда новая компания будет ждать подтверждения, поступит жалоба на отзыв, или фото/договор будут ждать проверки.",
        kindBusinessAwaitingApproval: "Компания ожидает подтверждения",
        kindReviewReported: "Жалоба на отзыв",
        kindPhotoPending: "Фото требует проверки",
        kindContractPending: "Договор требует публикации",
        noBusinessLink: "—"
      },
      loginPage: {
        title: "Вход в админ-консоль",
        subtitle: "Вход возможен только по логину и паролю.",
        usernameLabel: "Логин",
        passwordLabel: "Пароль",
        submit: "Войти",
        submitting: "Вход…",
        errorGeneric: "Неверный логин или пароль."
      },
      dataPage: {
        title: "База данных",
        subtitle: "Только для чтения: таблицы, количество строк и объём хранилища.",
        tablesTitle: "Таблицы",
        colTable: "Таблица",
        colRows: "Строки",
        viewTable: "Открыть",
        storageTitle: "Хранилище (Storage)",
        storageSubtitle: "Бакеты, количество объектов и общий объём.",
        storageNotConfigured: "Supabase Storage не настроен.",
        colBucket: "Бакет",
        colObjects: "Объекты",
        colBytes: "Объём",
        bucketPublic: "Открытый",
        bucketPrivate: "Закрытый",
        backToTables: "Вернуться к списку таблиц",
        tableRowsTitle: "Строки",
        rowsEmptyTitle: "Строк нет",
        rowsEmptyText: "В этой таблице пока нет записей.",
        limitLabel: "Строк на странице",
        prevPage: "Назад",
        nextPage: "Далее",
        totalRowsLabel: "Всего",
        truncatedNotice: "Из-за большого объёма подсчёт неполный — это нижняя оценка.",
        redactedNotice: "Конфиденциальные столбцы (пароль, email, телефон и т.д.) замаскированы."
      }
    }
  },
  en: {
    menu: {
      section: "Main menu",
      overview: "Dashboard",
      bookings: "Bookings",
      announcements: "Announcements",
      packages: "Services & prices",
      reviews: "Reviews",
      analytics: "Analytics",
      customers: "Customers",
      settings: "Settings",
      plan: "Plan",
      upgrade: "Upgrade plan",
      viewPublic: "View public page",
      partnerPortal: "Partner Portal",
      mobileMenu: "Menu"
    },
    overview: {
      title: "Dashboard",
      visits30: "Visits (30 days)",
      unique30: "Unique visitors",
      reviewsTotal: "Total reviews",
      avgRating: "Average rating",
      vsNote: "last 30 days",
      last7: "in the last 7 days",
      visitsChart: "Daily visits",
      ratingDist: "Rating distribution",
      completeness: "Profile completeness",
      completenessHint: "Complete profiles rank higher in search.",
      published: "Published announcements",
      activePackages: "Active services",
      pendingNote: "Your business is awaiting admin approval. The profile becomes public after review.",
      welcome: "Welcome back, here's what's happening today.",
      totalBookings: "Total bookings",
      revenue: "Revenue",
      activeDiscounts: "Active discounts",
      businessHealth: "Business health",
      rangeWeek: "Week",
      rangeMonth: "Month",
      recentBookings: "Recent bookings",
      viewAll: "View all",
      statusClaimed: "Claimed",
      statusPending: "Pending approval"
    },
    bookings: {
      title: "Bookings",
      subtitle: "Record bookings taken by phone or walk-in right here.",
      newTitle: "New booking",
      customerPhone: "Customer phone",
      serviceName: "Service",
      startsAt: "Start time",
      endsAt: "End time (optional)",
      depositAmount: "Deposit, UZS (optional)",
      submit: "Add booking",
      submitting: "Saving…",
      upcoming: "Upcoming",
      filterAll: "All",
      table: {
        customer: "Customer",
        phone: "Phone",
        service: "Service",
        when: "When",
        status: "Status",
        actions: "Actions"
      },
      statuses: {
        pending: "Pending",
        confirmed: "Confirmed",
        canceled: "Canceled",
        completed: "Completed",
        no_show: "No-show"
      },
      confirm: "Confirm",
      confirming: "Confirming…",
      complete: "Mark completed",
      completing: "Marking…",
      cancel: "Cancel",
      canceling: "Canceling…",
      noShow: "Mark no-show",
      noShowing: "Marking…",
      emptyTitle: "No bookings yet",
      emptyBody:
        "Record a booking here whenever a customer calls or walks in. Once it's marked \"Completed\", the customer is added to your customer list automatically, and picks up a \"verified visit\" badge if they leave a review.",
      noEndsAt: "—"
    },
    announcements: {
      title: "Announcements",
      subtitle: "Publish news, discounts, and broadcasts.",
      newTitle: "New announcement",
      kind: "Type",
      kinds: { news: "News", discount: "Discount", broadcast: "Broadcast" },
      formTitle: "Title",
      formBody: "Body",
      discountPercent: "Discount (%)",
      startsAt: "Start date",
      endsAt: "End date",
      submit: "Publish",
      saveDraft: "Save as draft",
      statuses: { draft: "Draft", published: "Published", archived: "Archived" },
      publish: "Publish",
      archive: "Archive",
      remove: "Delete",
      empty: "No announcements yet.",
      table: { title: "Title", kind: "Type", status: "Status", date: "Date", actions: "Actions" }
    },
    packages: {
      title: "Services & prices",
      subtitle: "Your service list is visible to customers on the public page.",
      newTitle: "New service",
      name: "Name",
      description: "Description",
      price: "Price (UZS)",
      submit: "Add",
      activate: "Activate",
      deactivate: "Deactivate",
      remove: "Delete",
      empty: "No services yet.",
      table: { name: "Service", price: "Price", status: "Status", actions: "Actions" },
      active: "Active",
      inactive: "Inactive"
    },
    reviews: {
      title: "Reviews",
      subtitle: "Respond to customer reviews officially.",
      empty: "No reviews yet.",
      reply: "Reply",
      replyPlaceholder: "Official reply text",
      send: "Send",
      replied: "Replied",
      exportCsv: "Download CSV"
    },
    settings: {
      title: "Settings",
      subtitle: "Business details appear on the public page.",
      profile: "Business details",
      name: "Name",
      legalName: "Legal name",
      taxId: "Tax ID (9 digits)",
      address: "Address",
      district: "District",
      phone: "Phone",
      email: "Email",
      website: "Website",
      instagram: "Instagram",
      telegram: "Telegram",
      hours: "Opening hours",
      description: "Description",
      save: "Save",
      subscription: "Subscription",
      plan: "Plan",
      status: "Status",
      renews: "Next payment",
      subStatuses: {
        active: "Active",
        trial: "Trial",
        invoice_pending: "Invoice pending",
        canceled: "Canceled"
      }
    },
    register: {
      title: "Register your business",
      subtitle:
        "Fill in the details. An administrator reviews the application; the dashboard unlocks fully after approval.",
      basics: "Basic details",
      category: "Category",
      contactSection: "Contacts",
      legalSection: "Legal details (Uzbekistan)",
      legalHint: "Tax ID is optional but speeds up approval.",
      submit: "Register",
      submitting: "Submitting…",
      failedTitle: "Registration didn't go through",
      failedBody: "Nothing was saved. Try again — this will not create a duplicate business.",
      retry: "Try again",
      signInFirst: "Sign in first",
      signInText: "An account is required to register a business.",
      signIn: "Sign in",
      brandWordmark: "Manzil for Business",
      brandTagline: "Empower your local business.",
      brandSubline:
        "Create your Manzil profile — customers find you, leave reviews, and get in touch.",
      mobileKicker: "Partner portal registration",
      namePlaceholder: "e.g. Chinor Cafe",
      categoryPlaceholder: "Select a category",
      signUpPrompt: "No account yet?",
      signUpCta: "Sign up"
    },
    plans: {
      title: "Choose a plan",
      subtitle: "You can change it at any time.",
      note: "Paid plans are invoiced. The plan activates once payment is confirmed.",
      choose: "Choose",
      choosing: "Redirecting to payment…",
      checkoutFailedTitle: "Checkout didn't start",
      checkoutFailedBody: "Nothing was charged. Try again, or choose a different plan.",
      retry: "Try again"
    },
    photos: {
      title: "Your business photos",
      subtitle: "Photos you upload appear immediately and can be chosen as the cover.",
      uploadLabel: "Upload a photo",
      makeCover: "Make cover",
      isCoverLabel: "Cover photo",
      pendingLabel: "Under review",
      empty: "No photos yet.",
      skip: "Skip for now",
      continueCta: "Go to dashboard"
    },
    analytics: {
      title: "Analytics",
      subtitle: "How customers find you and what they do next.",
      window: "Last 30 days",
      visits: "Visits",
      unique: "Unique visitors",
      rating: "Average rating",
      revenue: "Revenue",
      visitTrend: "Visit trend",
      funnel: "Customer actions",
      ratingTrend: "Rating trend",
      bookings: "Bookings",
      noData: "No data yet. This fills in once visitors arrive.",
      ofViews: "of views",
      upgradeTitle: "Analytics is on the Pro plan",
      upgradeText: "Upgrade to see visits, customer actions, and your rating trend.",
      upgradeCta: "See plans",
      eventView: "Profile view",
      eventPhoto: "Photo view",
      eventDirections: "Directions",
      eventCall: "Call",
      eventMessage: "Message"
    },
    customers: {
      title: "Customers",
      subtitle: "Customer list, built automatically from bookings.",
      empty: "No customers yet. This fills in once your first booking is accepted.",
      colName: "Name / Phone",
      colLastVisit: "Last visit",
      colVisits: "Visits",
      colSpend: "Total spend",
      colTags: "Tags",
      colConsent: "Marketing consent",
      consentYes: "Yes",
      consentNo: "No",
      never: "Never"
    },
    customerDetail: {
      back: "Back to customers",
      notFound: "Customer not found",
      firstSeen: "First seen",
      profile: "Customer details",
      bookings: "Bookings",
      reviews: "Reviews",
      visits: "Visit history",
      noBookings: "No bookings yet",
      noReviews: "No reviews yet",
      noVisits: "No visits recorded",
      noAccountHint: "This customer is not linked to a Manzil account, so no reviews can be shown.",
      colService: "Service",
      colDate: "Date",
      colStatus: "Status",
      colAmount: "Amount",
      notes: "Notes",
      noNotes: "No notes"
    },
    terms: {
      section: "Terms & contract",
      hint: "You must accept the terms of service to register a business.",
      checkbox: "I have read and accept the terms of service and the public offer contract",
      read: "Read the terms",
      version: "Version",
      unavailable: "No terms document has been published yet. Registration will continue, but no acceptance record can be stored.",
      contractTitle: "Your contract",
      contractNo: "Contract number",
      download: "Download contract",
      noContract: "No contract has been generated yet.",
      accepted: "Accepted documents"
    },
    common: {
      signInPrompt: "Sign in to open the dashboard",
      noBusiness: "You have no business yet",
      noBusinessText: "Register a new business or claim an existing listing.",
      registerCta: "Add a business",
      switchBusiness: "Business"
    },
    admin: {
      accessRestricted: "Access restricted",
      accessRestrictedText:
        "This console is available to administrator accounts only. Sign in with an administrator account to continue.",
      signIn: "Sign in",
      kicker: "Admin console",
      title: "Platform control center",
      subtitle: "Company queue, content moderation, and notifications — all in one place.",
      statBusinesses: "Database listings",
      statPendingClaims: "Pending claims",
      statReviews: "Reviews",
      statCategories: "Categories",
      statModerationQueue: "Moderation queue",
      claimsKicker: "Claim queue",
      claimsTitle: "Pending business claims",
      claimsSubtitle: "Admins review, approve, or reject claims.",
      colBusiness: "Business",
      colRequester: "Requester",
      colNote: "Note",
      colActions: "Actions",
      approve: "Approve",
      reject: "Reject",
      claimsEmpty: "No pending claims.",
      reportsKicker: "Moderation queue",
      reportsTitle: "Open reports",
      reportsSubtitle: "Reported reviews and photos can be resolved or dismissed here.",
      colType: "Type",
      colReason: "Reason",
      colReporter: "Reporter",
      colDetail: "Detail",
      typeReview: "Reported review",
      typePhoto: "Reported photo",
      removeContent: "Remove content",
      dismissReport: "Dismiss report",
      reportsEmpty: "No open moderation reports.",
      nav: {
        overview: "Overview",
        companies: "Companies",
        notifications: "Notifications",
        notificationsUnread: "Notifications ({n})",
        roleFallback: "Admin"
      },
      common: {
        permissionDeniedTitle: "No permission",
        permissionDeniedText: "You do not have the permission required to view this section.",
        reasonLabel: "Reason",
        reasonHint: "At least 10 characters",
        viewDetail: "Details",
        statusUnclaimed: "Unclaimed",
        statusPendingClaim: "Awaiting approval",
        statusClaimed: "Claimed",
        statusSuspended: "Suspended",
        moderationPending: "Pending",
        moderationApproved: "Approved",
        moderationRejected: "Rejected"
      },
      overviewPage: {
        statsTitle: "Platform status",
        statPendingBusinesses: "Companies awaiting approval",
        statFlaggedReviews: "Reported reviews",
        statBannedUsers: "Banned users",
        statAdmins: "Active admins",
        noAnalyticsPermission: "You do not have permission to view statistics.",
        inboxTitle: "Unread notifications",
        inboxSubtitle: "Every entry links to the company it concerns.",
        inboxEmptyTitle: "The queue is empty",
        inboxEmptyText: "Entries appear here when a new company awaits approval, a review is reported, or a photo or contract is waiting for review.",
        markAllRead: "Mark all as read",
        markingAll: "Marking…",
        viewAll: "All notifications",
        noNotificationPermission: "You do not have permission to view notifications.",
        nothingTitle: "Nothing to show",
        nothingText: "No console permissions have been assigned to your account yet. Ask an administrator for access."
      },
      companiesPage: {
        title: "Companies",
        subtitle: "Search, filter by status, approve or reject.",
        searchPlaceholder: "Search by name, address, or district",
        searchSubmit: "Search",
        filterAll: "All",
        colName: "Company",
        colCategory: "Category",
        colLocation: "Location",
        colPhone: "Phone",
        colRating: "Rating",
        colOwner: "Owner",
        colCreated: "Created",
        colStatus: "Status",
        colActions: "Actions",
        noOwner: "No owner",
        approve: "Approve",
        approving: "Approving…",
        reject: "Reject",
        rejecting: "Rejecting…",
        reasonPlaceholder: "Reason for rejection (at least 10 characters)",
        emptyTitle: "No companies found",
        emptyText: "No company matches the search or status filter. Try clearing the filter.",
        view: "Open"
      },
      companyTabs: {
        overview: "Overview",
        consumers: "Customers",
        reviews: "Reviews",
        photos: "Photos",
        contracts: "Contracts",
        audit: "History"
      },
      companyDetail: {
        notFoundTitle: "Company not found",
        notFoundText: "This company does not exist, or you do not have permission to view it.",
        backToList: "Back to the company list",
        owner: "Owner",
        noOwner: "Not yet claimed",
        category: "Category",
        createdAt: "Created",
        claimedAt: "Claimed",
        neverClaimed: "Not yet claimed",
        rating: "Rating",
        reviewsCount: "reviews",
        plan: "Plan",
        planStatus: "Subscription status",
        planRenews: "Next payment",
        noSubscription: "No subscription (free plan)",
        featured: "Featured",
        featureOn: "Yes",
        featureOff: "No",
        featuringOn: "Add to featured",
        featuringOff: "Remove from featured",
        approve: "Approve company",
        approving: "Approving…",
        reject: "Reject company",
        rejecting: "Rejecting…",
        editTitle: "Edit details",
        editHint: "Only the fields you fill in are saved.",
        editName: "Name",
        editAddress: "Address",
        editDistrict: "District",
        editPhone: "Phone",
        editEmail: "Email",
        editWebsite: "Website",
        editPriceTier: "Price tier",
        editSubmit: "Save",
        editSubmitting: "Saving…",
        activityTitle: "Activity",
        activityVisits: "Visits",
        activityBookings: "Bookings",
        activityReviews: "Approved reviews",
        activityCustomers: "Customers"
      },
      consumersTab: {
        title: "Customers",
        subtitle: "This company's customers and review authors, in one list.",
        emptyTitle: "No customers",
        emptyText: "A customer appears here once a booking is accepted or a review is written.",
        colName: "Name",
        colContact: "Contact",
        colSource: "Source",
        colVisits: "Visits",
        colSpend: "Total spend",
        colLastVisit: "Last visit",
        colReviews: "Reviews",
        sourceCustomer: "Customer",
        sourceReviewer: "Review author",
        sourceBoth: "Customer + review author"
      },
      reviewsTab: {
        title: "Reviews",
        subtitle: "Moderate the reviews written about this company.",
        emptyTitle: "No reviews",
        emptyText: "No review has been written about this company yet.",
        colAuthor: "Author",
        colRating: "Rating",
        colText: "Text",
        colStatus: "Status",
        colReported: "Reports",
        colDate: "Date",
        colActions: "Actions",
        approve: "Approve",
        approving: "Approving…",
        reject: "Reject",
        rejecting: "Rejecting…",
        remove: "Remove",
        removing: "Removing…",
        reasonPlaceholder: "Reason (at least 10 characters)"
      },
      photosTab: {
        title: "Photos",
        subtitle: "Photos waiting to be reviewed.",
        emptyTitle: "No photos to review",
        emptyText: "Newly uploaded photos appear here.",
        fromReview: "Uploaded with a review",
        approve: "Approve",
        approving: "Approving…",
        reject: "Reject",
        rejecting: "Rejecting…",
        reasonPlaceholder: "Reason for rejection (at least 10 characters)"
      },
      contractsTab: {
        title: "Contracts",
        subtitle: "This company's contract and the documents it has accepted.",
        contractNo: "Contract number",
        contractVersion: "Template version",
        contractGenerated: "Generated",
        noContract: "No contract has been generated for this company yet.",
        acceptancesTitle: "Accepted documents",
        acceptancesEmpty: "No document has been accepted.",
        legalDocsTitle: "Global legal documents",
        legalDocsEmpty: "No document has been published yet.",
        colKind: "Type",
        colVersion: "Version",
        colLocale: "Language",
        colPublished: "Published",
        colAcceptances: "Acceptances",
        publishTitle: "Publish a new version",
        publishHint: "Acceptances are bound to an exact version — existing text is never edited, only a new version is published.",
        publishKind: "Document type",
        publishVersion: "Version",
        publishLocale: "Language",
        publishDocTitle: "Title",
        publishBody: "Text",
        publishSubmit: "Publish",
        publishSubmitting: "Publishing…",
        kindTerms: "Terms of use",
        kindPrivacy: "Privacy policy",
        kindContract: "Contract template"
      },
      auditTab: {
        title: "History",
        subtitle: "Every admin action taken on this company.",
        emptyTitle: "History is empty",
        emptyText: "No admin action has been recorded for this company yet.",
        colWhen: "When",
        colActor: "Admin",
        colAction: "Action",
        colReason: "Reason",
        colTarget: "Target"
      },
      notificationsPage: {
        title: "Notifications",
        subtitle: "Every event that needs a human's attention.",
        filterAll: "All",
        filterUnread: "Unread",
        markAllRead: "Mark all as read",
        markingAll: "Marking…",
        markRead: "Mark as read",
        markingRead: "Marking…",
        colKind: "Type",
        colTitle: "Title",
        colBusiness: "Company",
        colCreated: "When",
        colStatus: "Status",
        colActions: "Actions",
        statusUnread: "Unread",
        statusRead: "Read",
        emptyTitle: "No notifications",
        emptyText: "Entries appear here when a new company awaits approval, a review is reported, or a photo or contract is waiting for review.",
        kindBusinessAwaitingApproval: "Company awaiting approval",
        kindReviewReported: "Review reported",
        kindPhotoPending: "Photo needs review",
        kindContractPending: "Contract needs publishing",
        noBusinessLink: "—"
      },
      loginPage: {
        title: "Sign in to the admin console",
        subtitle: "Sign-in is by username and password only.",
        usernameLabel: "Username",
        passwordLabel: "Password",
        submit: "Sign in",
        submitting: "Signing in…",
        errorGeneric: "Incorrect username or password."
      },
      dataPage: {
        title: "Database",
        subtitle: "Read-only: tables, row counts, and storage size.",
        tablesTitle: "Tables",
        colTable: "Table",
        colRows: "Rows",
        viewTable: "Open",
        storageTitle: "Storage",
        storageSubtitle: "Buckets, object counts, and total size.",
        storageNotConfigured: "Supabase Storage is not configured.",
        colBucket: "Bucket",
        colObjects: "Objects",
        colBytes: "Size",
        bucketPublic: "Public",
        bucketPrivate: "Private",
        backToTables: "Back to the table list",
        tableRowsTitle: "Rows",
        rowsEmptyTitle: "No rows",
        rowsEmptyText: "This table has no records yet.",
        limitLabel: "Rows per page",
        prevPage: "Previous",
        nextPage: "Next",
        totalRowsLabel: "Total",
        truncatedNotice: "The count is incomplete because the table is large — this is a lower bound.",
        redactedNotice: "Sensitive columns (password, email, phone, and so on) are masked."
      }
    }
  }
};

export type CrmCopy = (typeof copy)["uz"];

export function getCrmCopy(locale: Locale): CrmCopy {
  return copy[locale] ?? copy.uz;
}
