import type { Locale } from "@manzil/shared";

const copy = {
  uz: {
    menu: {
      section: "Asosiy menyu",
      overview: "Boshqaruv paneli",
      announcements: "E'lonlar",
      packages: "Xizmatlar va narxlar",
      reviews: "Sharhlar",
      analytics: "Tahlil",
      customers: "Mijozlar",
      settings: "Sozlamalar",
      plan: "Tarif",
      upgrade: "Tarifni oshirish",
      viewPublic: "Ochiq sahifani ko'rish"
    },
    overview: {
      title: "Boshqaruv paneli",
      visits30: "Tashriflar (30 kun)",
      unique30: "Noyob mehmonlar",
      reviewsTotal: "Jami sharhlar",
      avgRating: "O'rtacha baho",
      vsNote: "so'nggi 30 kun",
      last7: "so'nggi 7 kunda",
      visitsChart: "Kunlik tashriflar",
      ratingDist: "Baholar taqsimoti",
      completeness: "Profil to'liqligi",
      completenessHint: "To'liq profil qidiruvda yuqoriroq ko'rinadi.",
      published: "Chop etilgan e'lonlar",
      activePackages: "Faol xizmatlar",
      pendingNote: "Biznesingiz admin tasdig'ini kutmoqda. Tasdiqdan so'ng profil ochiq sahifada ko'rinadi."
    },
    announcements: {
      title: "E'lonlar",
      subtitle: "Yangiliklar, chegirmalar va xabarlarni chop eting.",
      newTitle: "Yangi e'lon",
      kind: "Turi",
      kinds: { news: "Yangilik", discount: "Chegirma", broadcast: "Xabar" },
      formTitle: "Sarlavha",
      formBody: "Matn",
      discountPercent: "Chegirma (%)",
      startsAt: "Boshlanish sanasi",
      endsAt: "Tugash sanasi",
      submit: "Chop etish",
      saveDraft: "Qoralama sifatida saqlash",
      statuses: { draft: "Qoralama", published: "Chop etilgan", archived: "Arxiv" },
      publish: "Chop etish",
      archive: "Arxivlash",
      remove: "O'chirish",
      empty: "Hozircha e'lonlar yo'q.",
      table: { title: "Sarlavha", kind: "Turi", status: "Holat", date: "Sana", actions: "Amallar" }
    },
    packages: {
      title: "Xizmatlar va narxlar",
      subtitle: "Xizmatlar ro'yxati mijozlarga ochiq sahifada ko'rinadi.",
      newTitle: "Yangi xizmat",
      name: "Nomi",
      description: "Tavsif",
      price: "Narx (so'm)",
      submit: "Qo'shish",
      activate: "Faollashtirish",
      deactivate: "To'xtatish",
      remove: "O'chirish",
      empty: "Hozircha xizmatlar yo'q.",
      table: { name: "Xizmat", price: "Narx", status: "Holat", actions: "Amallar" },
      active: "Faol",
      inactive: "Faol emas"
    },
    reviews: {
      title: "Sharhlar",
      subtitle: "Mijozlar sharhlariga rasmiy javob bering.",
      empty: "Hozircha sharhlar yo'q.",
      reply: "Javob yozish",
      replyPlaceholder: "Rasmiy javob matni",
      send: "Yuborish",
      replied: "Javob berilgan",
      exportCsv: "CSV yuklab olish"
    },
    settings: {
      title: "Sozlamalar",
      subtitle: "Biznes ma'lumotlari ochiq sahifada ko'rinadi.",
      profile: "Biznes ma'lumotlari",
      name: "Nomi",
      legalName: "Yuridik nomi",
      taxId: "STIR (9 raqam)",
      address: "Manzil",
      district: "Tuman",
      phone: "Telefon",
      email: "Email",
      website: "Veb-sayt",
      instagram: "Instagram",
      telegram: "Telegram",
      hours: "Ish vaqti",
      description: "Tavsif",
      save: "Saqlash",
      subscription: "Obuna",
      plan: "Tarif",
      status: "Holat",
      renews: "Keyingi to'lov",
      subStatuses: {
        active: "Faol",
        trial: "Sinov",
        invoice_pending: "To'lov kutilmoqda",
        canceled: "Bekor qilingan"
      }
    },
    register: {
      title: "Biznesni ro'yxatdan o'tkazish",
      subtitle:
        "Ma'lumotlarni to'ldiring. Ariza admin tomonidan ko'rib chiqiladi va tasdiqlangach kabinet to'liq ochiladi.",
      basics: "Asosiy ma'lumotlar",
      category: "Kategoriya",
      contactSection: "Aloqa",
      legalSection: "Yuridik ma'lumotlar (O'zbekiston)",
      legalHint: "STIR ixtiyoriy, lekin tasdiqlashni tezlashtiradi.",
      submit: "Ro'yxatdan o'tkazish",
      submitting: "Yuborilmoqda…",
      failedTitle: "Ro'yxatdan o'tkazib bo'lmadi",
      failedBody: "Ma'lumotlar saqlanmadi. Qaytadan urinib ko'ring — takroriy biznes yaratilmaydi.",
      retry: "Qaytadan urinish",
      signInFirst: "Avval tizimga kiring",
      signInText: "Biznesni ro'yxatdan o'tkazish uchun hisob talab qilinadi.",
      signIn: "Kirish"
    },
    plans: {
      title: "Tarifni tanlang",
      subtitle: "Keyinroq istalgan vaqtda o'zgartirishingiz mumkin.",
      note: "Pullik tariflar uchun hisob-faktura yuboriladi. To'lov tasdiqlangach tarif faollashadi.",
      choose: "Tanlash",
      choosing: "To'lovga yo'naltirilmoqda…",
      checkoutFailedTitle: "To'lovni boshlab bo'lmadi",
      checkoutFailedBody: "Hech qanday summa yechilmadi. Qaytadan urinib ko'ring yoki boshqa tarifni tanlang.",
      retry: "Qaytadan urinish"
    },
    photos: {
      title: "Biznesingiz rasmlari",
      subtitle: "O'zingiz yuklagan rasmlar darhol ko'rinadi va asosiy rasm sifatida tanlanishi mumkin.",
      uploadLabel: "Rasm yuklash",
      makeCover: "Asosiy rasm qilish",
      isCoverLabel: "Asosiy rasm",
      pendingLabel: "Ko'rib chiqilmoqda",
      empty: "Hozircha rasm yo'q.",
      skip: "Hozircha o'tkazib yuborish",
      continueCta: "Boshqaruv paneliga o'tish"
    },
    analytics: {
      title: "Tahlil",
      subtitle: "Mijozlar sizni qanday topayotgani va nima qilayotgani.",
      window: "Oxirgi 30 kun",
      visits: "Tashriflar",
      unique: "Noyob mehmonlar",
      rating: "O'rtacha reyting",
      revenue: "Tushum",
      visitTrend: "Tashriflar dinamikasi",
      funnel: "Mijoz harakatlari",
      ratingTrend: "Reyting dinamikasi",
      bookings: "Bandlovlar",
      noData: "Hozircha ma'lumot yo'q. Ma'lumot tashriflar boshlangach paydo bo'ladi.",
      ofViews: "ko'rishlardan",
      upgradeTitle: "Tahlil Pro tarifida",
      upgradeText: "Tashriflar, mijoz harakatlari va reyting dinamikasini ko'rish uchun tarifni oshiring.",
      upgradeCta: "Tariflarni ko'rish",
      eventView: "Sahifa ko'rildi",
      eventPhoto: "Rasm ko'rildi",
      eventDirections: "Yo'nalish",
      eventCall: "Qo'ng'iroq",
      eventMessage: "Xabar"
    },
    customers: {
      title: "Mijozlar",
      subtitle: "Bandlovlardan avtomatik yig'ilgan mijozlar ro'yxati.",
      empty: "Hozircha mijozlar yo'q. Birinchi bandlov qabul qilinganda bu yerda paydo bo'ladi.",
      colName: "Ism / Telefon",
      colLastVisit: "Oxirgi tashrif",
      colVisits: "Tashriflar",
      colSpend: "Jami xarajat",
      colTags: "Teglar",
      colConsent: "Marketingga rozilik",
      consentYes: "Ha",
      consentNo: "Yo'q",
      never: "Hech qachon"
    },
    customerDetail: {
      back: "Mijozlar ro'yxatiga qaytish",
      notFound: "Mijoz topilmadi",
      firstSeen: "Birinchi marta",
      profile: "Mijoz ma'lumotlari",
      bookings: "Bandlovlar",
      reviews: "Sharhlar",
      visits: "Tashriflar tarixi",
      noBookings: "Bandlovlar yo'q",
      noReviews: "Sharhlar yo'q",
      noVisits: "Tashriflar qayd etilmagan",
      noAccountHint: "Bu mijoz Manzil hisobiga ulanmagan, shuning uchun sharhlari ko'rsatilmaydi.",
      colService: "Xizmat",
      colDate: "Sana",
      colStatus: "Holat",
      colAmount: "Summa",
      notes: "Izohlar",
      noNotes: "Izoh yo'q"
    },
    terms: {
      section: "Shartlar va shartnoma",
      hint: "Ro'yxatdan o'tish uchun foydalanish shartlarini qabul qilishingiz kerak.",
      checkbox: "Men foydalanish shartlari va ommaviy oferta shartnomasini o'qib chiqdim va qabul qilaman",
      read: "Shartlarni o'qish",
      version: "Versiya",
      unavailable: "Shartlar hujjati hali chop etilmagan. Ro'yxatdan o'tish davom etadi, ammo qabul qilish yozuvi saqlanmaydi.",
      contractTitle: "Sizning shartnomangiz",
      contractNo: "Shartnoma raqami",
      download: "Shartnomani yuklab olish",
      noContract: "Shartnoma hali yaratilmagan.",
      accepted: "Qabul qilingan hujjatlar"
    },
    common: {
      signInPrompt: "Kabinet uchun tizimga kiring",
      noBusiness: "Sizda hali biznes yo'q",
      noBusinessText: "Yangi biznes qo'shing yoki mavjud listingni tasdiqlang.",
      registerCta: "Biznes qo'shish",
      switchBusiness: "Biznes"
    },
    admin: {
      accessRestricted: "Kirish cheklangan",
      accessRestrictedText:
        "Bu konsol faqat administrator hisoblari uchun ochiq. Davom etish uchun administrator hisobi bilan tizimga kiring.",
      signIn: "Kirish",
      kicker: "Admin konsoli",
      title: "Platforma boshqaruv markazi",
      subtitle: "Claim navbati, kontent moderatsiyasi va ma'lumotlar bazasi nazorati — barchasi shu yerda.",
      statBusinesses: "Database listinglari",
      statPendingClaims: "Pending claimlar",
      statReviews: "Sharhlar",
      statCategories: "Kategoriyalar",
      statModerationQueue: "Moderatsiya navbati",
      claimsKicker: "Claim navbati",
      claimsTitle: "Kutilayotgan biznes claimlar",
      claimsSubtitle: "Adminlar claimlarni tekshiradi, tasdiqlaydi yoki rad etadi.",
      colBusiness: "Biznes",
      colRequester: "So'rovchi",
      colNote: "Izoh",
      colActions: "Amallar",
      approve: "Tasdiqlash",
      reject: "Rad etish",
      claimsEmpty: "Hozircha pending claimlar yo'q.",
      reportsKicker: "Moderatsiya navbati",
      reportsTitle: "Ochiq shikoyatlar",
      reportsSubtitle: "Shikoyat qilingan sharhlar va rasmlarni shu yerda hal qilish yoki rad etish mumkin.",
      colType: "Turi",
      colReason: "Sababi",
      colReporter: "Shikoyatchi",
      colDetail: "Tafsilot",
      typeReview: "Shikoyat qilingan sharh",
      typePhoto: "Shikoyat qilingan rasm",
      removeContent: "Kontentni o'chirish",
      dismissReport: "Shikoyatni rad etish",
      reportsEmpty: "Ochiq moderatsiya shikoyatlari yo'q."
    }
  },
  ru: {
    menu: {
      section: "Основное меню",
      overview: "Панель управления",
      announcements: "Объявления",
      packages: "Услуги и цены",
      reviews: "Отзывы",
      analytics: "Аналитика",
      customers: "Клиенты",
      settings: "Настройки",
      plan: "Тариф",
      upgrade: "Повысить тариф",
      viewPublic: "Открытая страница"
    },
    overview: {
      title: "Панель управления",
      visits30: "Визиты (30 дней)",
      unique30: "Уникальные гости",
      reviewsTotal: "Всего отзывов",
      avgRating: "Средняя оценка",
      vsNote: "за последние 30 дней",
      last7: "за последние 7 дней",
      visitsChart: "Визиты по дням",
      ratingDist: "Распределение оценок",
      completeness: "Заполненность профиля",
      completenessHint: "Полный профиль выше показывается в поиске.",
      published: "Опубликованные объявления",
      activePackages: "Активные услуги",
      pendingNote: "Бизнес ожидает подтверждения администратора. После проверки профиль станет публичным."
    },
    announcements: {
      title: "Объявления",
      subtitle: "Публикуйте новости, скидки и сообщения.",
      newTitle: "Новое объявление",
      kind: "Тип",
      kinds: { news: "Новость", discount: "Скидка", broadcast: "Сообщение" },
      formTitle: "Заголовок",
      formBody: "Текст",
      discountPercent: "Скидка (%)",
      startsAt: "Дата начала",
      endsAt: "Дата окончания",
      submit: "Опубликовать",
      saveDraft: "Сохранить как черновик",
      statuses: { draft: "Черновик", published: "Опубликовано", archived: "Архив" },
      publish: "Опубликовать",
      archive: "В архив",
      remove: "Удалить",
      empty: "Объявлений пока нет.",
      table: { title: "Заголовок", kind: "Тип", status: "Статус", date: "Дата", actions: "Действия" }
    },
    packages: {
      title: "Услуги и цены",
      subtitle: "Список услуг виден клиентам на открытой странице.",
      newTitle: "Новая услуга",
      name: "Название",
      description: "Описание",
      price: "Цена (сум)",
      submit: "Добавить",
      activate: "Активировать",
      deactivate: "Остановить",
      remove: "Удалить",
      empty: "Услуг пока нет.",
      table: { name: "Услуга", price: "Цена", status: "Статус", actions: "Действия" },
      active: "Активна",
      inactive: "Неактивна"
    },
    reviews: {
      title: "Отзывы",
      subtitle: "Официально отвечайте на отзывы клиентов.",
      empty: "Отзывов пока нет.",
      reply: "Ответить",
      replyPlaceholder: "Текст официального ответа",
      send: "Отправить",
      replied: "Ответ отправлен",
      exportCsv: "Скачать CSV"
    },
    settings: {
      title: "Настройки",
      subtitle: "Данные бизнеса видны на открытой странице.",
      profile: "Данные бизнеса",
      name: "Название",
      legalName: "Юридическое название",
      taxId: "ИНН/СТИР (9 цифр)",
      address: "Адрес",
      district: "Район",
      phone: "Телефон",
      email: "Email",
      website: "Сайт",
      instagram: "Instagram",
      telegram: "Telegram",
      hours: "Часы работы",
      description: "Описание",
      save: "Сохранить",
      subscription: "Подписка",
      plan: "Тариф",
      status: "Статус",
      renews: "Следующий платёж",
      subStatuses: {
        active: "Активна",
        trial: "Пробный период",
        invoice_pending: "Ожидает оплаты",
        canceled: "Отменена"
      }
    },
    register: {
      title: "Регистрация бизнеса",
      subtitle:
        "Заполните данные. Заявку проверит администратор, после подтверждения кабинет откроется полностью.",
      basics: "Основные данные",
      category: "Категория",
      contactSection: "Контакты",
      legalSection: "Юридические данные (Узбекистан)",
      legalHint: "ИНН необязателен, но ускоряет подтверждение.",
      submit: "Зарегистрировать",
      submitting: "Отправляем…",
      failedTitle: "Не удалось зарегистрировать",
      failedBody: "Данные не сохранены. Попробуйте ещё раз — дубликат бизнеса не создастся.",
      retry: "Повторить",
      signInFirst: "Сначала войдите",
      signInText: "Для регистрации бизнеса требуется аккаунт.",
      signIn: "Войти"
    },
    plans: {
      title: "Выберите тариф",
      subtitle: "Его можно изменить в любой момент.",
      note: "Для платных тарифов выставляется счёт. Тариф активируется после подтверждения оплаты.",
      choose: "Выбрать",
      choosing: "Переходим к оплате…",
      checkoutFailedTitle: "Не удалось начать оплату",
      checkoutFailedBody: "Списания не произошло. Попробуйте ещё раз или выберите другой тариф.",
      retry: "Повторить"
    },
    photos: {
      title: "Фотографии бизнеса",
      subtitle: "Загруженные вами фото видны сразу и могут быть выбраны как обложка.",
      uploadLabel: "Загрузить фото",
      makeCover: "Сделать обложкой",
      isCoverLabel: "Обложка",
      pendingLabel: "На проверке",
      empty: "Фотографий пока нет.",
      skip: "Пропустить пока что",
      continueCta: "Перейти в панель управления"
    },
    analytics: {
      title: "Аналитика",
      subtitle: "Как клиенты находят вас и что делают дальше.",
      window: "Последние 30 дней",
      visits: "Визиты",
      unique: "Уникальные посетители",
      rating: "Средний рейтинг",
      revenue: "Выручка",
      visitTrend: "Динамика визитов",
      funnel: "Действия клиентов",
      ratingTrend: "Динамика рейтинга",
      bookings: "Брони",
      noData: "Пока нет данных. Они появятся, когда начнутся визиты.",
      ofViews: "от просмотров",
      upgradeTitle: "Аналитика на тарифе Pro",
      upgradeText: "Повысьте тариф, чтобы видеть визиты, действия клиентов и динамику рейтинга.",
      upgradeCta: "Посмотреть тарифы",
      eventView: "Просмотр страницы",
      eventPhoto: "Просмотр фото",
      eventDirections: "Маршрут",
      eventCall: "Звонок",
      eventMessage: "Сообщение"
    },
    customers: {
      title: "Клиенты",
      subtitle: "Список клиентов, автоматически собранный из броней.",
      empty: "Пока нет клиентов. Появятся здесь после первой принятой брони.",
      colName: "Имя / Телефон",
      colLastVisit: "Последний визит",
      colVisits: "Визиты",
      colSpend: "Всего потрачено",
      colTags: "Теги",
      colConsent: "Согласие на маркетинг",
      consentYes: "Да",
      consentNo: "Нет",
      never: "Никогда"
    },
    customerDetail: {
      back: "Назад к списку клиентов",
      notFound: "Клиент не найден",
      firstSeen: "Первый визит",
      profile: "Данные клиента",
      bookings: "Брони",
      reviews: "Отзывы",
      visits: "История визитов",
      noBookings: "Броней нет",
      noReviews: "Отзывов нет",
      noVisits: "Визиты не зафиксированы",
      noAccountHint: "Клиент не связан с аккаунтом Manzil, поэтому отзывы не отображаются.",
      colService: "Услуга",
      colDate: "Дата",
      colStatus: "Статус",
      colAmount: "Сумма",
      notes: "Заметки",
      noNotes: "Заметок нет"
    },
    terms: {
      section: "Условия и договор",
      hint: "Для регистрации необходимо принять условия использования.",
      checkbox: "Я прочитал(а) и принимаю условия использования и договор публичной оферты",
      read: "Прочитать условия",
      version: "Версия",
      unavailable: "Документ с условиями ещё не опубликован. Регистрация продолжится, но запись о принятии не будет сохранена.",
      contractTitle: "Ваш договор",
      contractNo: "Номер договора",
      download: "Скачать договор",
      noContract: "Договор ещё не сформирован.",
      accepted: "Принятые документы"
    },
    common: {
      signInPrompt: "Войдите, чтобы открыть кабинет",
      noBusiness: "У вас пока нет бизнеса",
      noBusinessText: "Добавьте новый бизнес или подтвердите существующий листинг.",
      registerCta: "Добавить бизнес",
      switchBusiness: "Бизнес"
    },
    admin: {
      accessRestricted: "Доступ ограничен",
      accessRestrictedText:
        "Эта консоль доступна только администраторам. Войдите под учётной записью администратора, чтобы продолжить.",
      signIn: "Войти",
      kicker: "Админ-консоль",
      title: "Центр управления платформой",
      subtitle: "Очередь заявок, модерация контента и контроль базы данных — всё в одном месте.",
      statBusinesses: "Записи в базе",
      statPendingClaims: "Заявки на рассмотрении",
      statReviews: "Отзывы",
      statCategories: "Категории",
      statModerationQueue: "Очередь модерации",
      claimsKicker: "Очередь заявок",
      claimsTitle: "Заявки на подтверждение бизнеса",
      claimsSubtitle: "Администраторы проверяют, подтверждают или отклоняют заявки.",
      colBusiness: "Бизнес",
      colRequester: "Заявитель",
      colNote: "Заметка",
      colActions: "Действия",
      approve: "Подтвердить",
      reject: "Отклонить",
      claimsEmpty: "Пока нет заявок на рассмотрении.",
      reportsKicker: "Очередь модерации",
      reportsTitle: "Открытые жалобы",
      reportsSubtitle: "Здесь можно рассмотреть или отклонить жалобы на отзывы и фото.",
      colType: "Тип",
      colReason: "Причина",
      colReporter: "Заявитель",
      colDetail: "Детали",
      typeReview: "Жалоба на отзыв",
      typePhoto: "Жалоба на фото",
      removeContent: "Удалить контент",
      dismissReport: "Отклонить жалобу",
      reportsEmpty: "Открытых жалоб модерации нет."
    }
  },
  en: {
    menu: {
      section: "Main menu",
      overview: "Dashboard",
      announcements: "Announcements",
      packages: "Services & prices",
      reviews: "Reviews",
      analytics: "Analytics",
      customers: "Customers",
      settings: "Settings",
      plan: "Plan",
      upgrade: "Upgrade plan",
      viewPublic: "View public page"
    },
    overview: {
      title: "Dashboard",
      visits30: "Visits (30 days)",
      unique30: "Unique visitors",
      reviewsTotal: "Total reviews",
      avgRating: "Average rating",
      vsNote: "last 30 days",
      last7: "in the last 7 days",
      visitsChart: "Daily visits",
      ratingDist: "Rating distribution",
      completeness: "Profile completeness",
      completenessHint: "Complete profiles rank higher in search.",
      published: "Published announcements",
      activePackages: "Active services",
      pendingNote: "Your business is awaiting admin approval. The profile becomes public after review."
    },
    announcements: {
      title: "Announcements",
      subtitle: "Publish news, discounts, and broadcasts.",
      newTitle: "New announcement",
      kind: "Type",
      kinds: { news: "News", discount: "Discount", broadcast: "Broadcast" },
      formTitle: "Title",
      formBody: "Body",
      discountPercent: "Discount (%)",
      startsAt: "Start date",
      endsAt: "End date",
      submit: "Publish",
      saveDraft: "Save as draft",
      statuses: { draft: "Draft", published: "Published", archived: "Archived" },
      publish: "Publish",
      archive: "Archive",
      remove: "Delete",
      empty: "No announcements yet.",
      table: { title: "Title", kind: "Type", status: "Status", date: "Date", actions: "Actions" }
    },
    packages: {
      title: "Services & prices",
      subtitle: "Your service list is visible to customers on the public page.",
      newTitle: "New service",
      name: "Name",
      description: "Description",
      price: "Price (UZS)",
      submit: "Add",
      activate: "Activate",
      deactivate: "Deactivate",
      remove: "Delete",
      empty: "No services yet.",
      table: { name: "Service", price: "Price", status: "Status", actions: "Actions" },
      active: "Active",
      inactive: "Inactive"
    },
    reviews: {
      title: "Reviews",
      subtitle: "Respond to customer reviews officially.",
      empty: "No reviews yet.",
      reply: "Reply",
      replyPlaceholder: "Official reply text",
      send: "Send",
      replied: "Replied",
      exportCsv: "Download CSV"
    },
    settings: {
      title: "Settings",
      subtitle: "Business details appear on the public page.",
      profile: "Business details",
      name: "Name",
      legalName: "Legal name",
      taxId: "Tax ID (9 digits)",
      address: "Address",
      district: "District",
      phone: "Phone",
      email: "Email",
      website: "Website",
      instagram: "Instagram",
      telegram: "Telegram",
      hours: "Opening hours",
      description: "Description",
      save: "Save",
      subscription: "Subscription",
      plan: "Plan",
      status: "Status",
      renews: "Next payment",
      subStatuses: {
        active: "Active",
        trial: "Trial",
        invoice_pending: "Invoice pending",
        canceled: "Canceled"
      }
    },
    register: {
      title: "Register your business",
      subtitle:
        "Fill in the details. An administrator reviews the application; the dashboard unlocks fully after approval.",
      basics: "Basic details",
      category: "Category",
      contactSection: "Contacts",
      legalSection: "Legal details (Uzbekistan)",
      legalHint: "Tax ID is optional but speeds up approval.",
      submit: "Register",
      submitting: "Submitting…",
      failedTitle: "Registration didn't go through",
      failedBody: "Nothing was saved. Try again — this will not create a duplicate business.",
      retry: "Try again",
      signInFirst: "Sign in first",
      signInText: "An account is required to register a business.",
      signIn: "Sign in"
    },
    plans: {
      title: "Choose a plan",
      subtitle: "You can change it at any time.",
      note: "Paid plans are invoiced. The plan activates once payment is confirmed.",
      choose: "Choose",
      choosing: "Redirecting to payment…",
      checkoutFailedTitle: "Checkout didn't start",
      checkoutFailedBody: "Nothing was charged. Try again, or choose a different plan.",
      retry: "Try again"
    },
    photos: {
      title: "Your business photos",
      subtitle: "Photos you upload appear immediately and can be chosen as the cover.",
      uploadLabel: "Upload a photo",
      makeCover: "Make cover",
      isCoverLabel: "Cover photo",
      pendingLabel: "Under review",
      empty: "No photos yet.",
      skip: "Skip for now",
      continueCta: "Go to dashboard"
    },
    analytics: {
      title: "Analytics",
      subtitle: "How customers find you and what they do next.",
      window: "Last 30 days",
      visits: "Visits",
      unique: "Unique visitors",
      rating: "Average rating",
      revenue: "Revenue",
      visitTrend: "Visit trend",
      funnel: "Customer actions",
      ratingTrend: "Rating trend",
      bookings: "Bookings",
      noData: "No data yet. This fills in once visitors arrive.",
      ofViews: "of views",
      upgradeTitle: "Analytics is on the Pro plan",
      upgradeText: "Upgrade to see visits, customer actions, and your rating trend.",
      upgradeCta: "See plans",
      eventView: "Profile view",
      eventPhoto: "Photo view",
      eventDirections: "Directions",
      eventCall: "Call",
      eventMessage: "Message"
    },
    customers: {
      title: "Customers",
      subtitle: "Customer list, built automatically from bookings.",
      empty: "No customers yet. This fills in once your first booking is accepted.",
      colName: "Name / Phone",
      colLastVisit: "Last visit",
      colVisits: "Visits",
      colSpend: "Total spend",
      colTags: "Tags",
      colConsent: "Marketing consent",
      consentYes: "Yes",
      consentNo: "No",
      never: "Never"
    },
    customerDetail: {
      back: "Back to customers",
      notFound: "Customer not found",
      firstSeen: "First seen",
      profile: "Customer details",
      bookings: "Bookings",
      reviews: "Reviews",
      visits: "Visit history",
      noBookings: "No bookings yet",
      noReviews: "No reviews yet",
      noVisits: "No visits recorded",
      noAccountHint: "This customer is not linked to a Manzil account, so no reviews can be shown.",
      colService: "Service",
      colDate: "Date",
      colStatus: "Status",
      colAmount: "Amount",
      notes: "Notes",
      noNotes: "No notes"
    },
    terms: {
      section: "Terms & contract",
      hint: "You must accept the terms of service to register a business.",
      checkbox: "I have read and accept the terms of service and the public offer contract",
      read: "Read the terms",
      version: "Version",
      unavailable: "No terms document has been published yet. Registration will continue, but no acceptance record can be stored.",
      contractTitle: "Your contract",
      contractNo: "Contract number",
      download: "Download contract",
      noContract: "No contract has been generated yet.",
      accepted: "Accepted documents"
    },
    common: {
      signInPrompt: "Sign in to open the dashboard",
      noBusiness: "You have no business yet",
      noBusinessText: "Register a new business or claim an existing listing.",
      registerCta: "Add a business",
      switchBusiness: "Business"
    },
    admin: {
      accessRestricted: "Access restricted",
      accessRestrictedText:
        "This console is available to administrator accounts only. Sign in with an administrator account to continue.",
      signIn: "Sign in",
      kicker: "Admin console",
      title: "Platform control center",
      subtitle: "Claim queue, content moderation, and database oversight — all in one place.",
      statBusinesses: "Database listings",
      statPendingClaims: "Pending claims",
      statReviews: "Reviews",
      statCategories: "Categories",
      statModerationQueue: "Moderation queue",
      claimsKicker: "Claim queue",
      claimsTitle: "Pending business claims",
      claimsSubtitle: "Admins review, approve, or reject claims.",
      colBusiness: "Business",
      colRequester: "Requester",
      colNote: "Note",
      colActions: "Actions",
      approve: "Approve",
      reject: "Reject",
      claimsEmpty: "No pending claims.",
      reportsKicker: "Moderation queue",
      reportsTitle: "Open reports",
      reportsSubtitle: "Reported reviews and photos can be resolved or dismissed here.",
      colType: "Type",
      colReason: "Reason",
      colReporter: "Reporter",
      colDetail: "Detail",
      typeReview: "Reported review",
      typePhoto: "Reported photo",
      removeContent: "Remove content",
      dismissReport: "Dismiss report",
      reportsEmpty: "No open moderation reports."
    }
  }
};

export type CrmCopy = (typeof copy)["uz"];

export function getCrmCopy(locale: Locale): CrmCopy {
  return copy[locale] ?? copy.uz;
}
